// This file is automatically generated by qtc from "binding_handers.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line binding_handers.qtpl:1
package templates

//line binding_handers.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line binding_handers.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line binding_handers.qtpl:1
func StreamGenerateBindingHandlers(qw422016 *qt422016.Writer, prefix string, appPath string) {
	//line binding_handers.qtpl:1
	qw422016.N().S(`
`)
	//line binding_handers.qtpl:2
	if len(prefix) > 0 {
		//line binding_handers.qtpl:2
		qw422016.N().S(`
package 	`)
		//line binding_handers.qtpl:3
		qw422016.E().S(prefix)
		//line binding_handers.qtpl:3
		qw422016.N().S(`_handlers

import (
	"`)
		//line binding_handers.qtpl:6
		qw422016.E().S(appPath)
		//line binding_handers.qtpl:6
		qw422016.N().S(`/game/`)
		//line binding_handers.qtpl:6
		qw422016.E().S(prefix)
		//line binding_handers.qtpl:6
		qw422016.N().S(`_global"
)   


func BindRequestHandlers() {

	// 不要用大于 5000 的数字
	`)
		//line binding_handers.qtpl:13
		qw422016.E().S(prefix)
		//line binding_handers.qtpl:13
		qw422016.N().S(`_global.GS.BindRequestHandler(1, "request login ", ExampleHandler, true)



}

`)
		//line binding_handers.qtpl:19
	} else {
		//line binding_handers.qtpl:19
		qw422016.N().S(`
package 	handlers

import (
	"`)
		//line binding_handers.qtpl:23
		qw422016.E().S(appPath)
		//line binding_handers.qtpl:23
		qw422016.N().S(`/game/global"
)   


func BindRequestHandlers() {

	// 不要用小于 5001 的数字
	global.GS.BindRequestHandler(5001, "request login ", ExampleHandler, true)



}
`)
		//line binding_handers.qtpl:35
	}
	//line binding_handers.qtpl:35
	qw422016.N().S(`



`)
//line binding_handers.qtpl:39
}

//line binding_handers.qtpl:39
func WriteGenerateBindingHandlers(qq422016 qtio422016.Writer, prefix string, appPath string) {
	//line binding_handers.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line binding_handers.qtpl:39
	StreamGenerateBindingHandlers(qw422016, prefix, appPath)
	//line binding_handers.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line binding_handers.qtpl:39
}

//line binding_handers.qtpl:39
func GenerateBindingHandlers(prefix string, appPath string) string {
	//line binding_handers.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
	//line binding_handers.qtpl:39
	WriteGenerateBindingHandlers(qb422016, prefix, appPath)
	//line binding_handers.qtpl:39
	qs422016 := string(qb422016.B)
	//line binding_handers.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
	//line binding_handers.qtpl:39
	return qs422016
//line binding_handers.qtpl:39
}
