// This file is automatically generated by qtc from "common_protobuf.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line common_protobuf.qtpl:1
package templates

//line common_protobuf.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line common_protobuf.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line common_protobuf.qtpl:1
func StreamGenerateCommonProtobuf(qw422016 *qt422016.Writer, prefix string, appPath string) {
	//line common_protobuf.qtpl:1
	qw422016.N().S(`
syntax = "proto3";
`)
	//line common_protobuf.qtpl:3
	if len(prefix) > 0 {
		//line common_protobuf.qtpl:3
		qw422016.N().S(`
package `)
		//line common_protobuf.qtpl:4
		qw422016.E().S(prefix)
		//line common_protobuf.qtpl:4
		qw422016.N().S(`_pstructs;

`)
		//line common_protobuf.qtpl:6
	} else {
		//line common_protobuf.qtpl:6
		qw422016.N().S(`
package pstructs;

`)
		//line common_protobuf.qtpl:9
	}
	//line common_protobuf.qtpl:9
	qw422016.N().S(`

`)
//line common_protobuf.qtpl:11
}

//line common_protobuf.qtpl:11
func WriteGenerateCommonProtobuf(qq422016 qtio422016.Writer, prefix string, appPath string) {
	//line common_protobuf.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line common_protobuf.qtpl:11
	StreamGenerateCommonProtobuf(qw422016, prefix, appPath)
	//line common_protobuf.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line common_protobuf.qtpl:11
}

//line common_protobuf.qtpl:11
func GenerateCommonProtobuf(prefix string, appPath string) string {
	//line common_protobuf.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
	//line common_protobuf.qtpl:11
	WriteGenerateCommonProtobuf(qb422016, prefix, appPath)
	//line common_protobuf.qtpl:11
	qs422016 := string(qb422016.B)
	//line common_protobuf.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
	//line common_protobuf.qtpl:11
	return qs422016
//line common_protobuf.qtpl:11
}
