// This file is automatically generated by qtc from "dotConfig.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line dotConfig.qtpl:1
package templates

//line dotConfig.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line dotConfig.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line dotConfig.qtpl:1
func StreamGenerateDotConfigFile(qw422016 *qt422016.Writer) {
	//line dotConfig.qtpl:1
	qw422016.N().S(`
---
development:
  server:
    websocket:
      http_url: websocket
      ip_port: ":8080"
    tcp_server:
      ip_port: ":9998"
  database:
    user: root
    password: 

production:
  server:
    websocket:
      http_url: websocket
      ip_port: ":8080"
    tcp_server:
      ip_port: ":9998"
  database:
    user: root
    password:

`)
//line dotConfig.qtpl:25
}

//line dotConfig.qtpl:25
func WriteGenerateDotConfigFile(qq422016 qtio422016.Writer) {
	//line dotConfig.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line dotConfig.qtpl:25
	StreamGenerateDotConfigFile(qw422016)
	//line dotConfig.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line dotConfig.qtpl:25
}

//line dotConfig.qtpl:25
func GenerateDotConfigFile() string {
	//line dotConfig.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line dotConfig.qtpl:25
	WriteGenerateDotConfigFile(qb422016)
	//line dotConfig.qtpl:25
	qs422016 := string(qb422016.B)
	//line dotConfig.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line dotConfig.qtpl:25
	return qs422016
//line dotConfig.qtpl:25
}
