// This file is automatically generated by qtc from "example_struct.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line example_struct.qtpl:1
package templates

//line example_struct.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line example_struct.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line example_struct.qtpl:1
func StreamGenerateExampleStruct(qw422016 *qt422016.Writer, prefix string, appPath string) {
	//line example_struct.qtpl:1
	qw422016.N().S(`
`)
	//line example_struct.qtpl:2
	if len(prefix) > 0 {
		//line example_struct.qtpl:2
		qw422016.N().S(`
package 	`)
		//line example_struct.qtpl:3
		qw422016.E().S(prefix)
		//line example_struct.qtpl:3
		qw422016.N().S(`_structs
`)
		//line example_struct.qtpl:4
	} else {
		//line example_struct.qtpl:4
		qw422016.N().S(`
package 	structs
`)
		//line example_struct.qtpl:6
	}
	//line example_struct.qtpl:6
	qw422016.N().S(`

type Example struct{
    Name string

}

`)
//line example_struct.qtpl:13
}

//line example_struct.qtpl:13
func WriteGenerateExampleStruct(qq422016 qtio422016.Writer, prefix string, appPath string) {
	//line example_struct.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line example_struct.qtpl:13
	StreamGenerateExampleStruct(qw422016, prefix, appPath)
	//line example_struct.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line example_struct.qtpl:13
}

//line example_struct.qtpl:13
func GenerateExampleStruct(prefix string, appPath string) string {
	//line example_struct.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line example_struct.qtpl:13
	WriteGenerateExampleStruct(qb422016, prefix, appPath)
	//line example_struct.qtpl:13
	qs422016 := string(qb422016.B)
	//line example_struct.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line example_struct.qtpl:13
	return qs422016
//line example_struct.qtpl:13
}
