// This file is automatically generated by qtc from "example_hander.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line example_hander.qtpl:1
package templates

//line example_hander.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line example_hander.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line example_hander.qtpl:1
func StreamGenerateExampleHandler(qw422016 *qt422016.Writer, prefix string, appPath string, name string) {
	//line example_hander.qtpl:1
	qw422016.N().S(`
`)
	//line example_hander.qtpl:2
	if len(prefix) > 0 {
		//line example_hander.qtpl:2
		qw422016.N().S(`
package 	`)
		//line example_hander.qtpl:3
		qw422016.E().S(prefix)
		//line example_hander.qtpl:3
		qw422016.N().S(`_handlers

import (
	"`)
		//line example_hander.qtpl:6
		qw422016.E().S(appPath)
		//line example_hander.qtpl:6
		qw422016.N().S(`/game/`)
		//line example_hander.qtpl:6
		qw422016.E().S(prefix)
		//line example_hander.qtpl:6
		qw422016.N().S(`_global"
    "`)
		//line example_hander.qtpl:7
		qw422016.E().S(appPath)
		//line example_hander.qtpl:7
		qw422016.N().S(`/game/`)
		//line example_hander.qtpl:7
		qw422016.E().S(prefix)
		//line example_hander.qtpl:7
		qw422016.N().S(`_pstructs"
   	"`)
		//line example_hander.qtpl:8
		qw422016.E().S(appPath)
		//line example_hander.qtpl:8
		qw422016.N().S(`/game/`)
		//line example_hander.qtpl:8
		qw422016.E().S(prefix)
		//line example_hander.qtpl:8
		qw422016.N().S(`_structs"

	
	"torch/game_server"

	"github.com/go-playground/log"

)   


// rp is GameClienterResponser
func `)
		//line example_hander.qtpl:19
		qw422016.E().S(name)
		//line example_hander.qtpl:19
		qw422016.N().S(`Handler(s *game_server.RequestSession, rp game_server.Responser, rqParams *`)
		//line example_hander.qtpl:19
		qw422016.E().S(prefix)
		//line example_hander.qtpl:19
		qw422016.N().S(`_pstructs.RqExample) {

    log.Debug(`)
		//line example_hander.qtpl:21
		qw422016.E().S(prefix)
		//line example_hander.qtpl:21
		qw422016.N().S(`_global.MDB)

	log.Info("Example handler show")
    ex:=`)
		//line example_hander.qtpl:24
		qw422016.E().S(prefix)
		//line example_hander.qtpl:24
		qw422016.N().S(`_structs.Example{Name:"struct example"}
    log.Debug(ex)
	rp.Write(game_server.RK_WEBSOCKET, &`)
		//line example_hander.qtpl:26
		qw422016.E().S(prefix)
		//line example_hander.qtpl:26
		qw422016.N().S(`_pstructs.RpExample{Name:"example"})

}


`)
		//line example_hander.qtpl:31
	} else {
		//line example_hander.qtpl:31
		qw422016.N().S(`
package 	handlers

import (
	"`)
		//line example_hander.qtpl:35
		qw422016.E().S(appPath)
		//line example_hander.qtpl:35
		qw422016.N().S(`/game/global"
    "`)
		//line example_hander.qtpl:36
		qw422016.E().S(appPath)
		//line example_hander.qtpl:36
		qw422016.N().S(`/game/pstructs"
   	"`)
		//line example_hander.qtpl:37
		qw422016.E().S(appPath)
		//line example_hander.qtpl:37
		qw422016.N().S(`/game/structs"

	
	"torch/game_server"

	"github.com/go-playground/log"

)   


// rp is GameClienterResponser
func `)
		//line example_hander.qtpl:48
		qw422016.E().S(name)
		//line example_hander.qtpl:48
		qw422016.N().S(`Handler(s *game_server.RequestSession, rp game_server.Responser, rqParams *pstructs.RqExample) {

    log.Debug(global.MDB)

	log.Info("Example handler show")
    ex:=_structs.Example{Name:"struct example"}
    log.Debug(ex)
	rp.Write(game_server.RK_WEBSOCKET, pstructs.RpExample{Name:"example"})

}


`)
		//line example_hander.qtpl:60
	}
	//line example_hander.qtpl:60
	qw422016.N().S(`

func init() {
	addHandler(1, "request example ", ExampleHandler, true)

}

`)
//line example_hander.qtpl:67
}

//line example_hander.qtpl:67
func WriteGenerateExampleHandler(qq422016 qtio422016.Writer, prefix string, appPath string, name string) {
	//line example_hander.qtpl:67
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line example_hander.qtpl:67
	StreamGenerateExampleHandler(qw422016, prefix, appPath, name)
	//line example_hander.qtpl:67
	qt422016.ReleaseWriter(qw422016)
//line example_hander.qtpl:67
}

//line example_hander.qtpl:67
func GenerateExampleHandler(prefix string, appPath string, name string) string {
	//line example_hander.qtpl:67
	qb422016 := qt422016.AcquireByteBuffer()
	//line example_hander.qtpl:67
	WriteGenerateExampleHandler(qb422016, prefix, appPath, name)
	//line example_hander.qtpl:67
	qs422016 := string(qb422016.B)
	//line example_hander.qtpl:67
	qt422016.ReleaseByteBuffer(qb422016)
	//line example_hander.qtpl:67
	return qs422016
//line example_hander.qtpl:67
}
