// This file is automatically generated by qtc from "generate_protobuf_go_file.sh.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line generate_protobuf_go_file.sh.qtpl:1
package templates

//line generate_protobuf_go_file.sh.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line generate_protobuf_go_file.sh.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line generate_protobuf_go_file.sh.qtpl:1
func StreamGenerateProtobufGofile(qw422016 *qt422016.Writer, pstructsPath string, protobufPath string, protobufFile string) {
	//line generate_protobuf_go_file.sh.qtpl:1
	qw422016.N().S(`#!/bin/bash
echo GOPATH: ${GOPATH}
protoc --gofast_out=`)
	//line generate_protobuf_go_file.sh.qtpl:3
	qw422016.E().S(pstructsPath)
	//line generate_protobuf_go_file.sh.qtpl:3
	qw422016.N().S(` --proto_path=`)
	//line generate_protobuf_go_file.sh.qtpl:3
	qw422016.E().S(protobufPath)
	//line generate_protobuf_go_file.sh.qtpl:3
	qw422016.N().S(` `)
	//line generate_protobuf_go_file.sh.qtpl:3
	qw422016.E().S(protobufFile)
	//line generate_protobuf_go_file.sh.qtpl:3
	qw422016.N().S(`
`)
//line generate_protobuf_go_file.sh.qtpl:4
}

//line generate_protobuf_go_file.sh.qtpl:4
func WriteGenerateProtobufGofile(qq422016 qtio422016.Writer, pstructsPath string, protobufPath string, protobufFile string) {
	//line generate_protobuf_go_file.sh.qtpl:4
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line generate_protobuf_go_file.sh.qtpl:4
	StreamGenerateProtobufGofile(qw422016, pstructsPath, protobufPath, protobufFile)
	//line generate_protobuf_go_file.sh.qtpl:4
	qt422016.ReleaseWriter(qw422016)
//line generate_protobuf_go_file.sh.qtpl:4
}

//line generate_protobuf_go_file.sh.qtpl:4
func GenerateProtobufGofile(pstructsPath string, protobufPath string, protobufFile string) string {
	//line generate_protobuf_go_file.sh.qtpl:4
	qb422016 := qt422016.AcquireByteBuffer()
	//line generate_protobuf_go_file.sh.qtpl:4
	WriteGenerateProtobufGofile(qb422016, pstructsPath, protobufPath, protobufFile)
	//line generate_protobuf_go_file.sh.qtpl:4
	qs422016 := string(qb422016.B)
	//line generate_protobuf_go_file.sh.qtpl:4
	qt422016.ReleaseByteBuffer(qb422016)
	//line generate_protobuf_go_file.sh.qtpl:4
	return qs422016
//line generate_protobuf_go_file.sh.qtpl:4
}
