// This file is automatically generated by qtc from "global.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line global.qtpl:1
package templates

//line global.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line global.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line global.qtpl:1
func StreamGenerateGlobal(qw422016 *qt422016.Writer, prefix string) {
	//line global.qtpl:1
	qw422016.N().S(`
`)
	//line global.qtpl:2
	if len(prefix) > 0 {
		//line global.qtpl:2
		qw422016.N().S(`
package `)
		//line global.qtpl:3
		qw422016.E().S(prefix)
		//line global.qtpl:3
		qw422016.N().S(`_global
`)
		//line global.qtpl:4
	} else {
		//line global.qtpl:4
		qw422016.N().S(`
package global
`)
		//line global.qtpl:6
	}
	//line global.qtpl:6
	qw422016.N().S(`

import (
	"torch/game_server"

	"github.com/jinzhu/gorm"
	"github.com/tidwall/buntdb"
)

var (
	//GS Global GameServer pointer
	GS *game_server.GameServer
	//BDB Global buntdb pointer
	BDB *buntdb.DB

	MDB *gorm.DB
)

`)
//line global.qtpl:24
}

//line global.qtpl:24
func WriteGenerateGlobal(qq422016 qtio422016.Writer, prefix string) {
	//line global.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line global.qtpl:24
	StreamGenerateGlobal(qw422016, prefix)
	//line global.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line global.qtpl:24
}

//line global.qtpl:24
func GenerateGlobal(prefix string) string {
	//line global.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
	//line global.qtpl:24
	WriteGenerateGlobal(qb422016, prefix)
	//line global.qtpl:24
	qs422016 := string(qb422016.B)
	//line global.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
	//line global.qtpl:24
	return qs422016
//line global.qtpl:24
}
