// This file is automatically generated by qtc from "id_map.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line id_map.qtpl:1
package templates

//line id_map.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line id_map.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line id_map.qtpl:1
func StreamGenerateIdMapStruct(qw422016 *qt422016.Writer, prefix string, appPath string) {
	//line id_map.qtpl:1
	qw422016.N().S(`
`)
	//line id_map.qtpl:2
	if len(prefix) > 0 {
		//line id_map.qtpl:2
		qw422016.N().S(`
package 	`)
		//line id_map.qtpl:3
		qw422016.E().S(prefix)
		//line id_map.qtpl:3
		qw422016.N().S(`_structs
`)
		//line id_map.qtpl:4
	} else {
		//line id_map.qtpl:4
		qw422016.N().S(`
package 	structs
`)
		//line id_map.qtpl:6
	}
	//line id_map.qtpl:6
	qw422016.N().S(`

import (
`)
	//line id_map.qtpl:9
	if len(prefix) > 0 {
		//line id_map.qtpl:9
		qw422016.N().S(`
    "`)
		//line id_map.qtpl:10
		qw422016.E().S(appPath)
		//line id_map.qtpl:10
		qw422016.N().S(`/game/`)
		//line id_map.qtpl:10
		qw422016.E().S(prefix)
		//line id_map.qtpl:10
		qw422016.N().S(`_pstructs"
`)
		//line id_map.qtpl:11
	} else {
		//line id_map.qtpl:11
		qw422016.N().S(`
    "`)
		//line id_map.qtpl:12
		qw422016.E().S(appPath)
		//line id_map.qtpl:12
		qw422016.N().S(`/game/pstructs"
`)
		//line id_map.qtpl:13
	}
	//line id_map.qtpl:13
	qw422016.N().S(`
	"torch/game_server"
)

// IDMap  Map a pstructs to an int number
type IDMap struct {
	ID      uint16
	Typ     interface{}
	FillFun interface{}
	Asap    bool
}

// IDMapList an IDMap list
var IDMapList []IDMap

func init() {
	IDMapList = []IDMap{}

	// 从5000 开始
`)
	//line id_map.qtpl:32
	if len(prefix) > 0 {
		//line id_map.qtpl:32
		qw422016.N().S(`
    IDMapList = append(IDMapList, IDMap{5001, `)
		//line id_map.qtpl:33
		qw422016.E().S(prefix)
		//line id_map.qtpl:33
		qw422016.N().S(`_pstructs.ResponseHeader{}, nil, true})
   	IDMapList = append(IDMapList, IDMap{5002, `)
		//line id_map.qtpl:34
		qw422016.E().S(prefix)
		//line id_map.qtpl:34
		qw422016.N().S(`_pstructs.RpRequestReceived{}, nil, true})
   	IDMapList = append(IDMapList, IDMap{5003, `)
		//line id_map.qtpl:35
		qw422016.E().S(prefix)
		//line id_map.qtpl:35
		qw422016.N().S(`_pstructs.RpRequestComplete{}, nil, true})
   	IDMapList = append(IDMapList, IDMap{5004, `)
		//line id_map.qtpl:36
		qw422016.E().S(prefix)
		//line id_map.qtpl:36
		qw422016.N().S(`_pstructs.RpExample{}, nil, true})
`)
		//line id_map.qtpl:37
	} else {
		//line id_map.qtpl:37
		qw422016.N().S(`
    IDMapList = append(IDMapList, IDMap{5001, pstructs.ResponseHeader{}, nil, true})
   	IDMapList = append(IDMapList, IDMap{5002, pstructs.RpRequestReceived{}, nil, true})
   	IDMapList = append(IDMapList, IDMap{5003, pstructs.RpRequestComplete{}, nil, true})
   	IDMapList = append(IDMapList, IDMap{5004, pstructs.RpExample{}, nil, true})
`)
		//line id_map.qtpl:42
	}
	//line id_map.qtpl:42
	qw422016.N().S(`



	for _, m := range IDMapList {
		game_server.GameProtobufStructTypes.BindProtobufStructType(m.ID, m.Typ, m.FillFun, m.Asap)
	}

}
`)
//line id_map.qtpl:51
}

//line id_map.qtpl:51
func WriteGenerateIdMapStruct(qq422016 qtio422016.Writer, prefix string, appPath string) {
	//line id_map.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line id_map.qtpl:51
	StreamGenerateIdMapStruct(qw422016, prefix, appPath)
	//line id_map.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line id_map.qtpl:51
}

//line id_map.qtpl:51
func GenerateIdMapStruct(prefix string, appPath string) string {
	//line id_map.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
	//line id_map.qtpl:51
	WriteGenerateIdMapStruct(qb422016, prefix, appPath)
	//line id_map.qtpl:51
	qs422016 := string(qb422016.B)
	//line id_map.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
	//line id_map.qtpl:51
	return qs422016
//line id_map.qtpl:51
}
