// This file is automatically generated by qtc from "scene.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line scene.qtpl:1
package templates

//line scene.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line scene.qtpl:1
import "strings"

//line scene.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line scene.qtpl:2
func StreamGenerateScene(qw422016 *qt422016.Writer, name string) {
	//line scene.qtpl:2
	qw422016.N().S(`

package scenes

import (
	"torch/game_server"
	"torch/scene_server"
	"errors"
	"fmt"
	"sync"
	"time"


	"gopkg.in/mgo.v2/bson"
)

const ROUND_DURATION = 1

type `)
	//line scene.qtpl:20
	qw422016.E().S(strings.Title(name))
	//line scene.qtpl:20
	qw422016.N().S(`Scene struct {
	id         bson.ObjectId
	rp game_server.Responser

	startedAt       int64
	lastProcessTick int64
	rwMu            sync.RWMutex
}



func (`)
	//line scene.qtpl:31
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:31
	qw422016.N().S(` *`)
	//line scene.qtpl:31
	qw422016.E().S(strings.Title(name))
	//line scene.qtpl:31
	qw422016.N().S(`Scene) Id() bson.ObjectId {
	return `)
	//line scene.qtpl:32
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:32
	qw422016.N().S(`.id
}

func (`)
	//line scene.qtpl:35
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:35
	qw422016.N().S(` *`)
	//line scene.qtpl:35
	qw422016.E().S(strings.Title(name))
	//line scene.qtpl:35
	qw422016.N().S(`Scene) Start(rp game_server.Responser, args ...interface{}) (bson.ObjectId, error) {

	if len(args) > 0 {
		u := args[0].(*structs.User)
		`)
	//line scene.qtpl:39
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:39
	qw422016.N().S(`.id = bson.NewObjectId()
		`)
	//line scene.qtpl:40
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:40
	qw422016.N().S(`.startedAt = time.Now().UnixNano()
		`)
	//line scene.qtpl:41
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:41
	qw422016.N().S(`.rp = rp
		return `)
	//line scene.qtpl:42
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:42
	qw422016.N().S(`.id, nil

	}
	return bson.NewObjectId(), errors.New("Not found user")
}

func (`)
	//line scene.qtpl:48
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:48
	qw422016.N().S(` *`)
	//line scene.qtpl:48
	qw422016.E().S(strings.Title(name))
	//line scene.qtpl:48
	qw422016.N().S(`Scene) End(rp game_server.Responser) (bool, error) {
	return false, nil
}

func (`)
	//line scene.qtpl:52
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:52
	qw422016.N().S(` *`)
	//line scene.qtpl:52
	qw422016.E().S(strings.Title(name))
	//line scene.qtpl:52
	qw422016.N().S(`Scene) WhetherEndScene() bool {
	runTime := time.Now().UnixNano() - `)
	//line scene.qtpl:53
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:53
	qw422016.N().S(`.startedAt
	if time.Duration(runTime) > (ROUND_DURATION * time.Minute) {

		return true
	}
	return false
}

func (`)
	//line scene.qtpl:61
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:61
	qw422016.N().S(` *`)
	//line scene.qtpl:61
	qw422016.E().S(strings.Title(name))
	//line scene.qtpl:61
	qw422016.N().S(`Scene) ProcessTick(t time.Time) {

	`)
	//line scene.qtpl:63
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:63
	qw422016.N().S(`.lastProcessTick = t.UnixNano()

}

func (`)
	//line scene.qtpl:67
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:67
	qw422016.N().S(` *`)
	//line scene.qtpl:67
	qw422016.E().S(strings.Title(name))
	//line scene.qtpl:67
	qw422016.N().S(`Scene) ProcessSignal(signal int) {
}

func (`)
	//line scene.qtpl:70
	qw422016.E().S(strings.ToLower(name))
	//line scene.qtpl:70
	qw422016.N().S(` *`)
	//line scene.qtpl:70
	qw422016.E().S(name)
	//line scene.qtpl:70
	qw422016.N().S(`Scene) ProcessCmd(cmd *scene_server.Cmd) {
	switch cmd.Paramater.(type) {
	}
}
`)
//line scene.qtpl:74
}

//line scene.qtpl:74
func WriteGenerateScene(qq422016 qtio422016.Writer, name string) {
	//line scene.qtpl:74
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line scene.qtpl:74
	StreamGenerateScene(qw422016, name)
	//line scene.qtpl:74
	qt422016.ReleaseWriter(qw422016)
//line scene.qtpl:74
}

//line scene.qtpl:74
func GenerateScene(name string) string {
	//line scene.qtpl:74
	qb422016 := qt422016.AcquireByteBuffer()
	//line scene.qtpl:74
	WriteGenerateScene(qb422016, name)
	//line scene.qtpl:74
	qs422016 := string(qb422016.B)
	//line scene.qtpl:74
	qt422016.ReleaseByteBuffer(qb422016)
	//line scene.qtpl:74
	return qs422016
//line scene.qtpl:74
}
